### ISSUE TITLE
Create new ClusterRole and ClusterRoleBinding for Cloud9 workspace

### ISSUE THREAD

**Issue by jicowan** [aws-samples/eks-security-compromised-cluster-remediation#20]
The role assigned to the Cloud9 workspace should only have permission to **list** Kubernetes secrets. Please update the `aws-auth` ConfigMap to use the following ClusterRole and ClusterRoleBinding: 

### ClusterRole 
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: custom-cluster-role
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - endpoints
  - replicationcontrollers
  - services
  - bindings
  - nodes
  - persistentvolumeclaims
  - podtemplates
  - persistentvolumes
  - resourcequotas
  - configmaps
  - events
  - componentstatuses
  - limitranges
  - namespaces
  - pods
  verbs:
  - '*'
- apiGroups:
  - apiregistration.k8s.io
  resources:
  - apiservices
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  - controllerrevisions
  - daemonsets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - '*'
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - '*'
- apiGroups:
  - authorization.k8s.io
  resources:
  - selfsubjectaccessreviews
  - localsubjectaccessreviews
  - selfsubjectrulesreviews
  - subjectaccessreviews
  verbs:
  - '*'
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - '*'
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - '*'
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - '*'
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  - ingressclasses
  - networkpolicies
  verbs:
  - '*'
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - '*'
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - '*'
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - roles
  - clusterrolebindings
  - rolebindings
  verbs:
  - '*'
- apiGroups:
  - storage.k8s.io
  resources:
  - volumeattachments
  - csinodes
  - csidrivers
  - storageclasses
  verbs:
  - '*'
- apiGroups:
  - storage.k8s.io
  resources:
  - csistoragecapacities
  verbs:
  - '*'
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  - mutatingwebhookconfigurations
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - scheduling.k8s.io
  resources:
  - priorityclasses
  verbs:
  - '*'
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - '*'
- apiGroups:
  - node.k8s.io
  resources:
  - runtimeclasses
  verbs:
  - '*'
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - '*'
- apiGroups:
  - flowcontrol.apiserver.k8s.io
  resources:
  - flowschemas
  - prioritylevelconfigurations
  verbs:
  - '*'
- apiGroups:
  - crd.k8s.amazonaws.com
  resources:
  - eniconfigs
  verbs:
  - '*'
- apiGroups:
  - vpcresources.k8s.aws
  resources:
  - securitygrouppolicies
  verbs:
  - '*'
- apiGroups: 
  - ""
  resources: 
  - secrets
  verbs: 
  - 'list'
```

### ClusterRoleBinding
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: custom-rolebinding
subjects:
- kind: Group
  name: pseudo-admin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: custom-cluster-role
  apiGroup: rbac.authorization.k8s.io
```
